# https://fluxcd.io/flux/components/helm/helmreleases/
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prometheus-operator-crds
  namespace: monitoring
spec:
  install:
    crds: CreateReplace
    replace: true
  releaseName: prometheus-operator-crds
  interval: 30m
  chart:
    # https://artifacthub.io/packages/helm/prometheus-community/prometheus-operator-crds
    spec:
      chart: prometheus-operator-crds
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
      version: "*"
      interval: 12h
  values:
    crds:
      # https://docs.victoriametrics.com/operator/integrations/prometheus/
      # The default behavior of the operator is as follows:
      #   1. It converts all existing Prometheus ServiceMonitor, PodMonitor, PrometheusRule, Probe and ScrapeConfig objects into corresponding VictoriaMetrics Operator objects.
      #   2. It syncs updates (including labels) from Prometheus ServiceMonitor, PodMonitor, PrometheusRule, Probe and ScrapeConfig objects to corresponding VictoriaMetrics Operator objects.
      #   3. It DOES NOT delete converted objects after original ones are deleted.
      alertmanagerconfigs:
        enabled: true
      podmonitors:
        enabled: true
      probes:
        enabled: true
      prometheusrules:
        enabled: true
      scrapeconfigs:
        enabled: true
      servicemonitors:
        enabled: true

      alertmanagers:
        enabled: false
      prometheuses:
        enabled: false
      prometheusagents:
        enabled: false
      thanosrulers:
        enabled: false
