---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # https://docs.konghq.com/kubernetes-ingress-controller/3.4.x/get-started/
  # - https://github.com/kubernetes-sigs/gateway-api/releases/download/v1.3.0/standard-install.yaml
  - ./gateway-api-v1.3.0-standard-install.yaml
  - ./helm-repo.yaml
  - ./helm-release.yaml
