---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # https://docs.konghq.com/kubernetes-ingress-controller/3.4.x/get-started/
  - ./helm-repo.yaml
  - ./helm-release.yaml
