apiVersion: networkaddonsoperator.network.kubevirt.io/v1
kind: NetworkAddonsConfig
metadata:
  name: cluster
spec:
  ovs: {} # openvswitch cni plugin
  # multus-cni is required by ovs cni plugin.
  # We need to customize some parameters of multus-cni,
  # so, install it via helm chart bitnami/multus-cni instead
  # multus: {}
