---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # ========================================
  # Install KubeVirt
  # https://github.com/kubevirt/kubevirt/releases
  # https://github.com/kubevirt/kubevirt/releases/download/v1.3.0/kubevirt-cr.yaml
  # ========================================
  - ./custom-kubevirt-cr.yaml

  # ========================================
  # Install CDI(Containerized Data Importer)
  # https://github.com/kubevirt/containerized-data-importer
  # ========================================
  - ./cdi-cr-v1.60.2.yaml

  # ========================================
  # Install Cluster Network Addons Operator
  # https://github.com/kubevirt/cluster-network-addons-operator/tree/main?tab=readme-ov-file#deployment
  # ========================================
  - ./custom-networkaddonsconfig.yaml
  - ./kubevirt-metrics.yaml
