# https://fluxcd.io/flux/components/helm/helmreleases/
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: openobserve-collector
  namespace: openobserve-collector
spec:
  install:
    crds: CreateReplace
    replace: true
  releaseName: openobserve-collector
  interval: 30m
  chart:
    spec:
      chart: openobserve-collector
      sourceRef:
        kind: HelmRepository
        name: openobserve-collector
        namespace: flux-system
      version: "0.3.*"
      interval: 12h
  # https://github.com/openobserve/openobserve-helm-chart/blob/main/charts/openobserve-collector/values.yaml
  values:
    exporters:
      otlphttp/openobserve:
        endpoint: http://o2-openobserve-router.openobserve.svc.cluster.local:5080/api/default
        headers:
          Authorization: Basic < base64 encoded auth >
      otlphttp/openobserve_k8s_events:
        endpoint: http://o2-openobserve-router.openobserve.svc.cluster.local:5080/api/default
        headers:
          Authorization: Basic < base64 encoded auth >
          stream-name: k8s_events
