---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # opentelemetry-operator
  - https://github.com/open-telemetry/opentelemetry-operator/releases/download/v0.108.0/opentelemetry-operator.yaml
  # openobserve-collector
  - ./helm-repo.yaml
  - ./helm-release.yaml
