kind: will-be-ignored
metadata:
    name: will-be-ignored
spec:
    values:
        exporters:
            otlphttp/openobserve:
                endpoint: http://o2-openobserve-router.openobserve.svc.cluster.local:5080/api/default
                headers:
                    # All auth values are encrypted via sops command:
                    #   sops --age=${AGE_RECIPIENT} --encrypt --in-place --encrypted-regex "Authorization" helmrelease-openobserve-collector.yaml
                    # Read repo's README.md for more details about how to encrypt the values.
                    #
                    Authorization: ENC[AES256_GCM,data:j4FVyD6bUTI7NVV/PngKyz+aWmgcbCVSk/m66tNYxdQOrtSv7Amq9vQDtr6hBdL7dFY=,iv:Q/E7IIWeBAeSE/CsoCWhBKvvwM7CpOWH92Pu3vr56Xk=,tag:l/gFVL89dYMg3xaRjT/c+w==,type:str]
            otlphttp/openobserve_k8s_events:
                endpoint: http://o2-openobserve-router.openobserve.svc.cluster.local:5080/api/default
                headers:
                    Authorization: ENC[AES256_GCM,data:nK2ZY35Qjsqa516Dv8Pkgc56LznnqF26R5CX3xVcTQteP6B+E+d2JrGFWJU5FrlQUYw=,iv:pMvJpkXeo6VXTgnTXlRhsOFYjGtgslw8QXsu9CFfzPY=,tag:DchzPUtM8/sHVHt0g5071w==,type:str]
                    stream-name: k8s_events
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1l5ml2kesuwzx9zdeh4sla7ftxd2nx0zq8ypvw8s0rttzm9s6hyks044vwr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQMGxaMTFkSUU4Nlc3cVBK
            eXlUSWtTeWp5MmdGR0RXT2ZiSjdTR25zUlFvCkt5Q002THlRRGEyODBxVUhuWVJ5
            eCtOUnYxb0IzUzFEVnB6QW8zMzU2YkkKLS0tIDhEdnhWQUFHdzVWeEYrL0hMTGl3
            SFFZSVFNS0loUE9Nbm5tT2pSeDhEbWMKFkeQz2rbrTIeD76jeaUhKFGHVOGDw6Wo
            zbDh7lDn9kV38rcqHrx8BfRE6D03EOALxR9km1h/VOhXbOu4NONv3Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-06T09:09:57Z"
    mac: ENC[AES256_GCM,data:wv6kYUUh6Y2OxvuyEYis5vSuXWEyqBjvszC+AjIT3N5GaXfJMZUn+DJxUKY5LliJak0pjYGC9NgVH4kZlnpu5s/cFrWglO2zTmjqaLvlv0Z8MpzhNurYFWC6NGumjpj1wsFEVF2xh7USyuXJpbkaPEfZ+pYKOk0shj1cLK23wEs=,iv:kvr1Y+CbqkgvdiXHFbNccHtJaAZQEgnnlpzN+Pzcc58=,tag:fvSa9bIDGgX6nPsL5uxVdA==,type:str]
    pgp: []
    encrypted_regex: Authorization
    version: 3.8.1
