kind: will-be-ignored
metadata:
  name: will-be-ignored
spec:
  values:
    loki:
      # Enables authentication through the X-Scope-OrgID header, which must be present
      # if true. If false, the OrgID will always be set to 'fake'.
      auth_enabled: true
      schemaConfig:
        # https://grafana.com/docs/loki/latest/operations/storage/schema/
        configs:
          # for a new install, use a recent date in the past.
          - from: "2025-06-01"
            # s3 / filesystem
            object_store: s3
            # tsdb only
            store: tsdb
            # v13 is the latest
            schema: v13
            index:
              # any value without spaces is acceptable.
              prefix: index_
              # must be 24h
              period: 24h
      storage:
        # Loki requires a bucket for chunks and the ruler. GEL requires a third bucket for the admin API.
        type: s3
        bucketNames: # for object storage
          chunks: k3s-test-1-loki-chunks

