kind: will-be-ignored
metadata:
  name: will-be-ignored
spec:
  values:
    loki:
      schemaConfig:
        # https://grafana.com/docs/loki/latest/operations/storage/schema/
        configs:
          # for a new install, use a recent date in the past.
          - from: "2025-06-01"
            # s3 / filesystem
            object_store: s3
            # tsdb only
            store: tsdb
            # v13 is the latest
            schema: v13
            index:
              # any value without spaces is acceptable.
              prefix: index_
              # must be 24h
              period: 24h
      storage:
        # Loki requires a bucket for chunks and the ruler. GEL requires a third bucket for the admin API.
        type: s3
        bucketNames: # for object storage
          chunks: k3s-test-1-loki-chunks
      # ============================================================================
      # Storage Retentaion
      # It's recommended to add a lifecycle policy on you object storage bucket.
      # to delete all the logs older than [retention_period + 1 day].
      # To assure the old logs get deleted.
      # https://grafana.com/docs/loki/latest/operations/storage/retention/
      # ============================================================================
      # Compact multiple index files in the table into a single index file per tenant per day.
      compactor:
        compaction_interval: 10m
        retention_enabled: true
        retention_delete_delay: 2h
        retention_delete_worker_count: 150
        delete_request_store: s3
      limits_config:
        reject_old_samples: true
        reject_old_samples_max_age: 168h
        max_query_lookback: 168h # 7 days
        # delete logs older than this period
        retention_period: 168h
        retention_stream:
          # keey only 1 day for dev logs
          - selector: '{namespace="dev"}'
            priority: 1
            period: 24h
        max_cache_freshness_per_query: 10m
        split_queries_by_interval: 15m
        query_timeout: 60s
        max_query_parallelism: 32
        max_concurrent_tail_requests: 10
        # OTEL related
        # https://grafana.com/docs/loki/latest/send-data/otel/
        allow_structured_metadata: true
        # otlp_config:
        #   resource_attributes:
        #     ignore_defaults: true
        #     attributes_config:
        #       - action: index_label
        #         attributes:
        #           - service.group
