---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # deploy monitoring stack first
  - ../../base/victoria-metrics/
  - ../../base/cert-manager/
  - ../../base/kong-gateway/
