---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # deploy monitoring stack first
  - ../../base/victoria-metrics/
  - ../../base/cert-manager/
  - ../../base/gateway-api/
  # - ../../base/kong-gateway/
  - ../../base/istio/
  - ../../base/kiali/
  - ../../base/k6/
  - ../../base/loki/
  - ../../base/otel-collector/
patches:
  - path: ./helmrelease-victoria-metrics.yaml
    target:
      group: helm.toolkit.fluxcd.io
      kind: HelmRelease
      name: victoria-metrics-k8s-stack
  - path: ./helmrelease-loki.yaml
    target:
      group: helm.toolkit.fluxcd.io
      kind: HelmRelease
      name: loki
  - path: ./helmrelease-otel-collector.yaml
    target:
      group: helm.toolkit.fluxcd.io
      kind: HelmRelease
      name: otel-collector
