---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # deploy monitoring stack first
  - ../../base/victoria-metrics/
  - ../../base/cert-manager/
  # - ../../base/kong-gateway/
  - ../../base/istio/
  - ../../base/kiali/
  - ../../base/openobserve/
  # - ../../base/openobserve-collector/
  - ../../base/k6/

patches:
  - path: ./helmrelease-victoria-metrics.yaml
    target:
      group: helm.toolkit.fluxcd.io
      kind: HelmRelease
      name: victoria-metrics-k8s-stack
      namespace: monitoring
  - path: ./helmrelease-openobserve.yaml
    target:
      group: helm.toolkit.fluxcd.io
      kind: HelmRelease
      name: openobserve
      namespace: openobserve
  - path: ./helmrelease-openobserve-collector.yaml
    target:
      group: helm.toolkit.fluxcd.io
      kind: HelmRelease
      name: openobserve-collector
      namespace: openobserve-collector
