# https://fluxcd.io/flux/components/helm/helmreleases/

---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: cilium
  namespace: kube-system
spec:
  releaseName: cilium
  interval: 30m
  chart:
    spec:
      chart: cilium
      sourceRef:
        kind: HelmRepository
        name: cilium
        namespace: flux-system
      interval: 12h
  # https://artifacthub.io/packages/helm/cilium/cilium/1.16.0
  values:
    cni:
      # disable this one for istio-cni
      # https://istio.io/latest/docs/ambient/install/platform-prerequisites/#cilium
      exclusive: false

