# https://fluxcd.io/flux/components/helm/helmreleases/

---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cilium
  namespace: kube-system
spec:
  releaseName: cilium
  interval: 30m
  chart:
    spec:
      chart: cilium
      sourceRef:
        kind: HelmRepository
        name: cilium
        namespace: flux-system
      interval: 12h
      version: "1.17.*"
  # https://github.com/cilium/cilium/tree/v1.17.0/install/kubernetes/cilium
  values:
    # To intergrate with Istio, set the following values:
    # https://docs.cilium.io/en/latest/network/servicemesh/istio/
    cni:
      exclusive: false
    socketLB:
      hostNamespaceOnly: true

