# https://fluxcd.io/flux/components/helm/helmreleases/
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: k6-operator
  namespace: k6
spec:
  install:
    crds: CreateReplace
    replace: true
  releaseName: k6-operator
  interval: 30m
  chart:
    spec:
      chart: k6-operator
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: k6-operator
        namespace: flux-system
      interval: 12h
  # https://github.com/grafana/k6-operator/blob/main/charts/k6-operator/values.yaml
  values:
    namespace:
      create: false

