---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ryan-windows-11-rootdisk
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi
  storageClassName: longhorn
---
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: ryan-windows-11
spec:
  runStrategy: Always
  template:
    metadata:
      labels:
        kubevirt.io/vm: ryan-windows-11
        kubevirt.io/os: win11
    spec:
      terminationGracePeriodSeconds: 30
      domain:
        cpu:
          # this sets the cores
          cores: 4
          # get CPU on the VM close to the node one
          model: host-model
        resources:
          requests:
            memory: 8192M
        features:
          acpi: {}
          apic: {}
          hyperv:
            relaxed: {}
            spinlocks:
              spinlocks: 8191
            vapic: {}
          smm: {}  # required by secure boot
        clock:
          utc: {}
          timer:
            hpet:
              present: false
            pit:
              tickPolicy: delay
            rtc:
              tickPolicy: catchup
            hyperv: {}
        firmware:
          bootloader:
            efi:
              persistent: true
              # disable secure boot to start from iso image
              secureBoot: false
          uuid: 5d307ca9-b3ef-428c-8861-06e72d69f223
        devices:
          tpm:
            persistent: true
          disks:
            - name: windows-11-iso
              cdrom:
                bus: sata
              # boot from iso image to install windows
              # you need to remove this disk after installation
              bootOrder: 1
            - name: rootdisk
              disk:
                bus: virtio
            - name: virtiocontainerdisk
              # Any other disk you want to use, must go before virtioContainerDisk.
              # KubeVirt boots from disks in order ther are defined.
              # Therefore virtioContainerDisk, must be after bootable disk.
              # Other option is to choose boot order explicitly:
              #  - https://kubevirt.io/api-reference/v0.13.2/definitions.html#_v1_disk
              # NOTE: You either specify bootOrder explicitely or sort the items in
              #       disks. You can not do both at the same time.
              # bootOrder: 2
              cdrom:
                bus: sata
          interfaces:
            - name: defaultnetwork
              masquerade: {}
              model: e1000
            - name: ovs-net
              bridge: {}
              model: e1000
      networks:
        - name: defaultnetwork
          pod: {}
        - name: ovs-net
          multus:
            # References to a NetworkAttachmentDefinition CRD object
            networkName: ovs-conf
      volumes:
        - name: rootdisk
          persistentVolumeClaim:
            claimName: ryan-windows-11-rootdisk
        - dataVolume:
            name: windows-11-iso
          name: windows-11-iso
        - containerDisk:
            image: quay.io/kubevirt/virtio-container-disk
          name: virtiocontainerdisk
  dataVolumeTemplates:
    - metadata:
        name: windows-11-iso
      spec:
        pvc:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 10Gi
        source:
          http:
            url: "http://file.writefor.fun/iso/zh-cn_windows_11_consumer_editions_version_22h2_updated_oct_2022_x64_dvd_8f62ad3d.iso"
