---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ryan-windows-11-rootdisk
  annotations:
    # fluxcd - merge the server-side configs
    kustomize.toolkit.fluxcd.io/ssa: Merge
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 60Gi
  storageClassName: longhorn-critical
  # NOTE: lock down the volume name to avoid creating a new one
  # This should only be used when you want to reuse the volume(like recreating the VM).
  volumeName: pvc-54f6c5bd-70ef-4f46-84fe-1f1237083e59
---
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: ryan-windows-11
spec:
  instancetype:
    kind: VirtualMachineClusterInstancetype
    name: hpc-4vcpu-8gb
  preference:
    kind: VirtualMachineClusterPreference
    name: windows
  runStrategy: RerunOnFailure # https://kubevirt.io/user-guide/compute/run_strategies/
  template:
    metadata:
      labels:
        kubevirt.io/vm: ryan-windows-11
        kubevirt.io/os: win11
    spec:
      terminationGracePeriodSeconds: 30
      domain:
        firmware:
          bootloader:
            efi:
              persistent: true
              # disable secure boot to start from iso image
              secureBoot: false
          uuid: 5d307ca9-b3ef-428c-8861-06e72d69f223
        devices:
          rng: {}
          tpm:
            persistent: true
          disks:
            # - name: windows-11-iso
            #   cdrom:
            #     bus: sata
            #   # boot from iso image to install windows
            #   # you need to remove this disk after installation
            #   bootOrder: 1
            - name: rootdisk
              disk:
                bus: virtio
            - name: virtiocontainerdisk
              # Any other disk you want to use, must go before virtioContainerDisk.
              # KubeVirt boots from disks in order ther are defined.
              # Therefore virtioContainerDisk, must be after bootable disk.
              # Other option is to choose boot order explicitly:
              #  - https://kubevirt.io/api-reference/v0.13.2/definitions.html#_v1_disk
              # NOTE: You either specify bootOrder explicitely or sort the items in
              #       disks. You can not do both at the same time.
              # bootOrder: 2
              cdrom:
                bus: sata
          interfaces:
            - name: defaultnetwork
              masquerade: {}
              model: e1000
            - name: ovs-net
              bridge: {}
              model: e1000
      networks:
        - name: defaultnetwork
          pod: {}
        - name: ovs-net
          multus:
            # References to a NetworkAttachmentDefinition CRD object
            networkName: ovs-conf
      volumes:
        - name: rootdisk
          persistentVolumeClaim:
            claimName: ryan-windows-11-rootdisk
        # - dataVolume:
        #     name: windows-11-iso
        #   name: windows-11-iso
        - containerDisk:
            image: quay.io/kubevirt/virtio-container-disk
          name: virtiocontainerdisk
  # dataVolumeTemplates:
  #   - metadata:
  #       name: windows-11-iso
  #     spec:
  #       pvc:
  #         # iso will be used only once, it's useless after installation
  #         storageClassName: longhorn-critical
  #         accessModes:
  #           - ReadWriteOnce
  #         resources:
  #           requests:
  #             storage: 10Gi
  #       source:
  #         http:
  #           url: "http://kubevirt-file.writefor.fun/iso/zh-cn_windows_11_consumer_editions_version_22h2_updated_oct_2022_x64_dvd_8f62ad3d.iso"
