kind: will-be-ignored
metadata:
  name: will-be-ignored
spec:
  values:
    vmagent:
      spec:
        scrapeInterval: 20s
        externalLabels:
          # For multi-cluster setups it is useful to use "cluster" label to identify the metrics source.
          cluster: kubevirt-lab-1
          env: kubevirtt
      ingress:
        hosts:
          - kubevirt-vmagent.writefor.fun
