---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # deploy monitoring stack first
  - ../../base/victoria-metrics/
  - ../../base/cert-manager/
  - ../../base/kong-gateway/
  - ../../base/kubevirt/
  # - ../../base/longhorn/ # longhorn is buggy on my 3-nodes homelab, remove it.

patches:
  - path: ./helmrelease-victoria-metrics.yaml
    target:
      group: helm.toolkit.fluxcd.io
      kind: HelmRelease
      name: victoria-metrics-k8s-stack
      namespace: monitoring
