apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: longhorn-critical
parameters:
  # -- Data locality of the default Longhorn StorageClass. (Options: "disabled", "best-effort", "strict-local")
  # https://longhorn.io/docs/1.6.2/high-availability/data-locality/
  dataLocality: best-effort
  fromBackup: ""
  fsType: ext4
  numberOfReplicas: "2"
  staleReplicaTimeout: "30"
  unmapMarkSnapChainRemoved: ignored
provisioner: driver.longhorn.io
# Retain critical volumes after deletion
reclaimPolicy: Retain
volumeBindingMode: Immediate
allowVolumeExpansion: true
