apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-path-test
provisioner: rancher.io/local-path
parameters:
  # nodePath: /var/lib/local-path-test
  pathPattern: "{{ .PVC.Namespace }}/{{ .PVC.Name }}"
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
