# https://fluxcd.io/flux/components/helm/helmreleases/
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: istio-base
  namespace: istio-system
spec:
  # The base chart contains the basic CRDs and cluster roles required to set up Istio
  # This should be installed prior to any other Istio component.
  releaseName: istio-base
  interval: 30m
  chart:
    spec:
      chart: base
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: flux-system
      interval: 12h
