---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/name: podinfo
  app.kubernetes.io/project: podinfo
  app.kubernetes.io/version: latest
resources:
  - ../../../../base/podinfo/
  - ./httproute.yaml
