---
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: k3s-test-1-master-3
spec:
  instancetype:
    kind: VirtualMachineClusterInstancetype
    name: m-4vcpu-16gb
  template:
    metadata:
      labels:
        kubevirt.io/vm: k3s-test-1-master-3
    spec:
      volumes:
        - dataVolume:
            name: k3s-test-1-master-3-disk
          name: rootdisk
  dataVolumeTemplates:
    - metadata:
        name: k3s-test-1-master-3-disk
      spec:
        pvc:
          # this is the rootdisk of the node, it contains critical data
          storageClassName: longhorn-test
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 50Gi
          # NOTE: lock down the volume name to avoid creating a new one
          # This should only be used when you want to reuse the volume(like recreating the VM).
          volumeName: pvc-bcf68b67-d33c-4826-ba84-63b2ebfe448d
        source:
          http:
            url: http://kubevirt-file.writefor.fun/vms/kubevirt-k3s-test-1-master-3.qcow2
