---
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: k3s-test-1-master-3
spec:
  instancetype:
    kind: VirtualMachineClusterInstancetype
    name: m-4vcpu-16gb
  template:
    metadata:
      labels:
        kubevirt.io/vm: k3s-test-1-master-3
    spec:
      volumes:
        - dataVolume:
            name: k3s-test-1-master-3-disk
          name: rootdisk
  dataVolumeTemplates:
    - metadata:
        name: k3s-test-1-master-3-disk
      spec:
        pvc:
          # this is the rootdisk of the node, it contains critical data
          storageClassName: longhorn-critical
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 50Gi
        source:
          http:
            url: http://file.writefor.fun/vms/kubevirt-k3s-test-1-master-3.qcow2
