---
apiVersion: v1
kind: Namespace
metadata:
  name: staging
  labels:
    eventing.knative.dev/injection: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: prod
  labels:
    eventing.knative.dev/injection: enabled
