---
apiVersion: v1
kind: Namespace
metadata:
  name: staging
  labels:
    eventing.knative.dev/injection: enabled
    istio.io/dataplane-mode: ambient
---
apiVersion: v1
kind: Namespace
metadata:
  name: prod
  labels:
    eventing.knative.dev/injection: enabled
    istio.io/dataplane-mode: ambient
