---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
---
apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager
---
apiVersion: v1
kind: Namespace
metadata:
  name: kong
---
apiVersion: v1
kind: Namespace
metadata:
  name: longhorn-system
---
apiVersion: v1
kind: Namespace
metadata:
  name: istio-system
---
apiVersion: v1
kind: Namespace
metadata:
  name: istio-ingress
---
apiVersion: v1
kind: Namespace
metadata:
  name: kiali-operator
---
apiVersion: v1
kind: Namespace
metadata:
  name: kubevirt
---
apiVersion: v1
kind: Namespace
metadata:
  name: cluster-network-addons
---
apiVersion: v1
kind: Namespace
metadata:
  name: cdi
---
apiVersion: v1
kind: Namespace
metadata:
  name: openobserve
---
apiVersion: v1
kind: Namespace
metadata:
  name: openobserve-collector
---
apiVersion: v1
kind: Namespace
metadata:
  name: k6
