---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: loki
  namespace: monitoring
spec:
  releaseName: loki
  interval: 30m
  chart:
    spec:
      chart: loki
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
      version: "6.*"
      interval: 12h
  # https://github.com/grafana/loki/tree/main/production/helm/loki
  values:
    # ==========================================
    # Deployment Mode & Resources
    # ==========================================
    # For My Private CA Certs
    global:
      extraVolumes: &extraVolumes
        - name: loki-certs
          secret:
            secretName: loki-certs
      extraVolumeMounts: &extraVolumeMounts
        - name: loki-certs
          mountPath: /data/certs
          readOnly: true
    deploymentMode: SingleBinary
    singleBinary:
      replicas: 1
      extraVolumes: *extraVolumes
      extraVolumeMounts: *extraVolumeMounts
      resources:
        limits:
          cpu: 2
          memory: 4Gi
        requests:
          cpu: 1
          memory: 2Gi
    # Zero out replica counts of other deployment modes
    backend:
      replicas: 0
    read:
      replicas: 0
    write:
      replicas: 0

    minio:
      enabled: false

    # we do not need this
    ruler:
      enabled: false

    # ==========================================
    # Loki's Config
    # ==========================================
    loki:
      commonConfig:
        replication_factor: 1
      ingester:
        chunk_encoding: snappy
      querier:
        # Default is 4, if you have enough memory and CPU you can increase, reduce if OOMing
        max_concurrent: 2
      # ============================================================================
      # Storage Configuration
      # ============================================================================
      storage:
        # Loki requires a bucket for chunks and the ruler. GEL requires a third bucket for the admin API.
        type: filesystem
        filesystem:
          chunks_directory: /var/loki/chunks
          rules_directory: /var/loki/rules
          admin_api_directory: /var/loki/admin
        # bucketNames: # Use a different bucket for each cluster
        #   chunks: xxx-loki-chunks
        s3:
          # bucketnames: {{ $.Values.loki.storage.bucketNames.chunks }}
          s3ForcePathStyle: true
          region: us-east-1
          insecure: false # Disable https on s3 connection.
          http_config:
            insecure_skip_verify: false # skip verifying the certificate chain and hostname.
            ca_file: /data/certs/ca.crt
          endpoint: https://minio.writefor.fun
          # Encrypt Command:
          #  sops --encrypt --age=${AGE_RECIPIENT}   --encrypted-regex 'Key' --in-place ./infra/controllers/overlays/k3s-test-1/helmrelease-loki.yaml
          #
          # Access Key
          accessKeyId: ENC[AES256_GCM,data:HrJOr3O+xaYCKpAwJrkqpbG/+N0=,iv:QbOKinnwmLgYtEmWrFJfnDjFXiNX4epU9ip7kGexzRs=,tag:kmoFR2dGj3uWLp1nWi7C5A==,type:str]
          # Secret Key
          secretAccessKey: ENC[AES256_GCM,data:vvSaDBWP2bV1grXFYfeZH/GV4Cbi8+w8BQXQLGdmLPVazHId8gd5MA==,iv:iQxC4ekcqo2K3kOM54HFP7AH5VGuvlNhjzrbMZIpbq8=,tag:GruLo0gVQ1LXC5eYdlIa3A==,type:str]
sops:
  age:
    - recipient: age15tr9ja4ll22ef3rw43v4mje47x8a03ruqap08f68hcu077tytq0q9e4h5y
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsZ05yVzJpWVByZGV4K1FL
        bGY3bDFqMll5NHJPOHB0dzhrVG0yVmJzU2pZCmlZOG15NDJOdkFwRE0xcFJrUENJ
        YUVHZmZmMm8zMERZUFk2c0psdDIwMU0KLS0tIExUb3hneS9ENEY0Y0RxWXB2QUlM
        bzdybFJ4T2RPWTRZOWRkVVVrUitFdlkKLumgsNsFjaB4iADdHe30YNAHsBH+THUm
        20aoWMAyMFyjOs9yKHXVSASch7iCv/ZqZHtH5Q3/pRhcZOomeMQEEQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-06-08T06:26:11Z"
  mac: ENC[AES256_GCM,data:ZIwFmbycsnam3yKW0NfC1jh9FNwuRrgyZtMsAbXGjd6Jr/QYsCdRduTcUEYdvphK3qnDTf9D/dCLJhc6/Cq9RgYU+Oxph2E3QuprhVxXy4MRaW2Ui50aQEsBkFKsi1hAgIxYAv43NL/33RgnaApy8bd9BcKuyhTrxOhinoz5mcg=,iv:W2h0ayx6bcfrWxsINL+jOoUFgwSFUXEy3FA5HmZixss=,tag:S/LOr0GxUw2rYHvKPKA+Tg==,type:str]
  encrypted_regex: Key
  version: 3.10.2
