---
apiVersion: instancetype.kubevirt.io/v1beta1
kind: VirtualMachineClusterInstancetype
metadata:
  name: highcpu-2vcpu-4gb
spec:
  cpu:
    guest: 2
    model: host-passthrough
  memory:
    guest: 4Gi
    maxGuest: 4Gi
