---
apiVersion: instancetype.kubevirt.io/v1beta1
kind: VirtualMachineClusterInstancetype
metadata:
  name: highcpu-4vcpu-8gb-dedicated
spec:
  cpu:
    guest: 4
    model: host-passthrough
    # pin the vCPUs to dedicated pCPUs and give the emulator its own
    dedicatedCPUPlacement: true
    isolateEmulatorThread: true
  memory:
    guest: 8Gi
    maxGuest: 8Gi
