---
apiVersion: instancetype.kubevirt.io/v1beta1
kind: VirtualMachineClusterInstancetype
metadata:
  name: highcpu-4vcpu-8gb-oc50
spec:
  cpu:
    guest: 4
    model: host-passthrough
  memory:
    guest: 8Gi
    maxGuest: 8Gi
    overcommitPercent: 50
