# https://kubevirt.io/user-guide/user_workloads/instancetypes/#virtualmachineinstancetype
---
apiVersion: instancetype.kubevirt.io/v1beta1
kind: VirtualMachineClusterInstancetype
metadata:
  name: c-1vcpu-2gb
spec:
  # https://kubevirt.io/api-reference/main/definitions.html#_v1beta1_cpuinstancetype
  cpu:
    # Required number of vCPUs to expose to the guest.
    guest: 1
    # Model specifies the CPU model inside the VMI.
    #   - host-passthrough  - get the same CPU as the node
    #   - host-model        - get CPU closest to the node one
    model: host-passthrough
  memory:
    # The delta between MaxGuest and Guest is the amount of memory that can be hot(un)plugged.
    guest: 2Gi
    maxGuest: 2Gi
    # Requests only 60% of the memory to be allocated to the VMI,
    # let the VMI pod comsume the other 60% of the memory when needed.
    overcommitPercent: 40
