---
apiVersion: instancetype.kubevirt.io/v1beta1
kind: VirtualMachineClusterInstancetype
metadata:
  name: tiny-2vcpu-2gb-oc60
spec:
  cpu:
    guest: 2
    model: host-model
  memory:
    guest: 2Gi
    maxGuest: 2Gi
    # request only 40% of the guest memory; the pod grows into the rest on demand
    overcommitPercent: 60
