---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # For Control Plane's High Availability
  - ./rbac.yaml
  - ./daemonset.yaml
  # For LoadBalancer Service's High Availability
  - ./cloud-controller.yaml
  - ./cloud-controller-configmap.yaml
