---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # the k3s API server's HA VIP
  - ../../base/kube-vip/
  - ../../base/cilium/
  - ../../base/csi-driver-nfs/
  - ../../base/secrets/
