---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps
  namespace: flux-system
spec:
  interval: 5m
  retryInterval: 10s
  dependsOn:
    - name: infra-namespaces
    - name: infra-controllers
    - name: infra-configs
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./apps/overlays/k3s-prod-1
  prune: true
  wait: true
  timeout: 1m
