apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: kiali
  namespace: kiali-operator
spec:
  parentRefs:
  - name: istio-default
    namespace: istio-ingress
  hostnames: ["kiali.writefor.fun"]
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /kiali
    backendRefs:
    - name: kiali
      port: 20001
