---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: otel-collector
  namespace: monitoring
spec:
  releaseName: otel-collector
  interval: 30m
  chart:
    spec:
      chart: opentelemetry-collector
      sourceRef:
        kind: HelmRepository
        name: open-telemetry
        namespace: flux-system
      version: "0.126.*"
      interval: 12h
  # https://github.com/open-telemetry/opentelemetry-helm-charts/tree/main/charts/opentelemetry-collector
  values:
    image:
      repository: "ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-k8s"
    command:
      name: "otelcol-k8s"

    mode: daemonset
    replicaCount: 1
    # https://opentelemetry.io/docs/kubernetes/collector/components/
    presets:
      kubernetesAttributes:
        enabled: true
        extractAllPodLabels: true
      logsCollection:
        enabled: true
        # Do not include the collector itself's log, to prevent log looping
        includeCollectorLogs: false

    config:
      receivers:
        jaeger: null
        prometheus: null
        zipkin: null
      exporters:
        otlphttp:
          endpoint: http://loki.monitoring.svc.cluster.local:3100/otlp
      service:
        pipelines:
          logs:
            exporters:
              - otlphttp
          traces: null
          metrics: null # we use vmagent for metrics collecting.
