apiVersion: instancetype.kubevirt.io/v1beta1
kind: VirtualMachineClusterPreference 
metadata:
  name: virtio
spec:
  devices:
    preferredDiskBus: virtio
    preferredInterfaceModel: virtio
    # use entropy collected by cluster nodes inside guest
    # to improve the quality of random numbers
    preferredRng: {}
