---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./kubevip/
  - ../../base/cilium/
  - ../../base/multus/
  # ca-certs / server-tls-certs into monitoring, kiali-operator, istio-ingress
  - ../../base/secrets/
