apiVersion: operator.victoriametrics.com/v1beta1
kind: VMPodScrape
metadata:
  name: loki-components
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: loki
  podMetricsEndpoints:
    - path: /metrics
      interval: 15s
      port: http-metrics
      relabelConfigs:
        - source_labels:
            - __meta_kubernetes_namespace
            - __meta_kubernetes_pod_label_app_kubernetes_io_name
            - __meta_kubernetes_pod_label_app_kubernetes_io_component
          separator: /
          regex: (.*)/(.*)/(.*)
          replacement: ${1}/${2}-${3}
          target_label: job
          action: replace
