---
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: k3s-prod-1-worker-2
spec:
  instancetype:
    kind: VirtualMachineClusterInstancetype
    name: c-4vcpu-8gb
  template:
    metadata:
      labels:
        kubevirt.io/vm: k3s-prod-1-worker-2
    spec:
      nodeSelector:
        # run on the node with the USB storage device
        kubernetes.io/hostname: kubevirt-youko
      volumes:
        - dataVolume:
            name: k3s-prod-1-worker-2-disk
          name: rootdisk
  dataVolumeTemplates:
    - metadata:
        name: k3s-prod-1-worker-2-disk
      spec:
        pvc:
          # this is the rootdisk of the node, it contains critical data
          storageClassName: longhorn-test
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 50Gi
        source:
          http:
            url: http://file.writefor.fun/vms/kubevirt-k3s-prod-1-worker-2.qcow2
