---
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: k3s-prod-1-worker-2
spec:
  instancetype:
    kind: VirtualMachineClusterInstancetype
    name: s-2vcpu-2gb
    # https://kubevirt.io/user-guide/user_workloads/instancetypes/#versioning
    revisionName: "" # we need to set this to empty when updating the instancetype
  template:
    metadata:
      labels:
        kubevirt.io/vm: k3s-prod-1-worker-2
    spec:
      volumes:
        - dataVolume:
            name: k3s-prod-1-worker-2-disk
          name: rootdisk
  dataVolumeTemplates:
    - metadata:
        name: k3s-prod-1-worker-2-disk
      spec:
        pvc:
          # this is the rootdisk of the node, it contains critical data
          storageClassName: longhorn-test
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 50Gi
          # NOTE: lock down the volume name to avoid creating a new one
          # This should only be used when you want to reuse the volume(like recreating the VM).
          volumeName: pvc-4e5c32d6-b94b-4daf-b4a4-00ed8ac52b60
        source:
          http:
            url: http://kubevirt-file.writefor.fun/vms/kubevirt-k3s-prod-1-worker-2.qcow2
