---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: longhorn-release
  namespace: longhorn-system
spec:
  chart:
    spec:
      chart: longhorn
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: longhorn-repo
      version: 1.6.2
  interval: 30m0s
  # https://github.com/longhorn/charts/blob/v1.6.x/charts/longhorn/values.yaml
  values:
    # https://longhorn.io/docs/1.6.2/best-practices/#volume-performance-optimization
    persistence:
      defaultClass: true
      # -- Filesystem type of the default Longhorn StorageClass.
      defaultFsType: ext4
      # 2 replicas to achieve data availability with better disk space usage or less impact to system performance
      defaultClassReplicaCount: 2
      # -- Data locality of the default Longhorn StorageClass. (Options: "disabled", "best-effort", "strict-local")
      # https://longhorn.io/docs/1.6.2/high-availability/data-locality/
      defaultDataLocality: strict-local # to gain better io performance
      # -- Reclaim policy that provides instructions for handling of a volume after its claim is released. (Options: "Retain", "Delete")
      reclaimPolicy: Delete
      migratable: false # disable by default, security concern
    defaultSettings:
      # https://longhorn.io/docs/1.6.2/high-availability/auto-balance-replicas/
      replicaAutoBalance: "best-effort"
      defaultReplicaCount: 2
      defaultDataLocality: strict-local
      snapshotDataIntegrity: fast-check
      # we have btrfs snapshot for host backup, so longhorn's snapshot is not necessary.
      snapshotMaxCount: 2
    ingress:
      enabled: true
      ingressClassName: kong
      host: longhorn.writefor.fun
