---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # ========================================
  # Install KubeVirt
  # ========================================
  - ./kubevirt-operator-v1.2.0.yaml

  # ========================================
  # Install CDI(Containerized Data Importer)
  # ========================================
  - ./cdi-operator-v1.58.2.yaml

  # ========================================
  # Install Cluster Network Addons Operator
  # ========================================
  # - ./cluster-network-addons-namespace-v0.91.0.yaml
  - ./cluster-network-addons-operator-v0.91.0.yaml
  - ./cluster-network-addons-config.crd-v0.91.0.yaml

patches:
  # We have create the those namespace in ./infra/namespaces,
  # so we need to delete the namespaces' creation in kubevirt-operator.yaml
  - path: delete-ns-kubevirt.yaml
  - path: delete-ns-cdi.yaml
  # - path: delete-ns-cluster-network-addons.yaml
