---
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: idols-aquamarine
spec:
  instancetype:
    kind: VirtualMachineClusterInstancetype
    name: mixed-8vcpu-11gb-dedicated
    # https://kubevirt.io/user-guide/user_workloads/instancetypes/#versioning
    revisionName: "" # we need to set this to empty when updating the instancetype
  preference:
    kind: VirtualMachineClusterPreference
    name: virtio
  template:
    metadata:
      labels:
        kubevirt.io/vm: idols-aquamarine
    spec:
      nodeSelector:
        # run on the node with the USB storage device
        kubernetes.io/hostname: kubevirt-youko
      domain:
        devices:
          # pass through the USB storage device
          hostDevices:
            - deviceName: kubevirt.io/usb-storage-unitek
              name: usb-storage
      volumes:
        - dataVolume:
            name: idols-aquamarine-disk
          name: rootdisk
  dataVolumeTemplates:
    - metadata:
        name: idols-aquamarine-disk
      spec:
        pvc:
          # this is the rootdisk of the node, it contains critical data
          storageClassName: local-path-critical
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 80Gi
          # NOTE: lock down the volume name to avoid creating a new one
          # This should only be used when you want to reuse the volume(like recreating the VM).
          # volumeName: ''
        # clone the golden image (shared NFS store) into the local disk
        source:
          pvc:
            name: golden-aquamarine
            namespace: vms
