---
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: k3s-prod-1-master-2
spec:
  instancetype:
    kind: VirtualMachineClusterInstancetype
    name: s-2vcpu-2gb
  preference:
    kind: VirtualMachineClusterPreference
    name: virtio
  runStrategy: Always
  template:
    metadata:
      labels:
        kubevirt.io/vm: k3s-prod-1-master-2
    spec:
      terminationGracePeriodSeconds: 30
      domain:
        devices:
          disks:
          - name: rootdisk
            disk:
              bus: virtio
          interfaces:
          - name: defaultnetwork
            masquerade: {}
          - name: ovs-net
            bridge: {}
      networks:
      - name: defaultnetwork
        pod: {}
      - name: ovs-net
        multus:
          # References to a NetworkAttachmentDefinition CRD object
          networkName: ovs-conf
      volumes:
      - dataVolume:
          name: k3s-prod-1-master-2-disk
        name: rootdisk
  dataVolumeTemplates:
  - metadata:
      name: k3s-prod-1-master-2-disk
    spec:
      pvc:
        storageClassName: longhorn-critical
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 50Gi
      source:
        http:
          url: http://file.writefor.fun/vms/kubevirt-k3s-prod-1-master-2.qcow2
