---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: vms
resources:
  # -- Prod Cluster
  - ./k3s-prod-1-master-1.yaml
  - ./k3s-prod-1-master-2.yaml
  - ./k3s-prod-1-master-3.yaml
  # -- Test Cluster
  - ./k3s-test-1-master-1.yaml
