# https://fluxcd.io/flux/components/helm/helmreleases/
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: kiali
  namespace: flux-system
spec:
  interval: 12h
  url: https://kiali.org/helm-charts


