---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: kiali
  namespace: kiali-operator
spec:
  # The base chart contains the basic CRDs and cluster roles required to set up Istio
  # This should be installed prior to any other Istio component.
  releaseName: kiali-operator
  interval: 30m
  chart:
    spec:
      chart: base
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: flux-system
      # istio <=> kiali Version Compatibility
      # https://kiali.io/docs/installation/installation-guide/prerequisites/
      version: "*"
      interval: 12h
  values:
    cr:
      create: true
      # the namespace where the CR will be created
      # (the default will be the operator namespace).
      namespace: kiali-operator
      spec:
        auth:
          strategy: anonymous
