name: test

# Copy from https://github.com/fluxcd/flux2-kustomize-helm-example/blob/main/.github/workflows/test.yaml

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [ '*' ]
    tags-ignore: [ '*' ]

jobs:
  manifests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup yq
        uses: fluxcd/pkg/actions/yq@main
      - name: Setup kubeconform
        uses: fluxcd/pkg/actions/kubeconform@main
      - name: Setup kustomize
        uses: fluxcd/pkg/actions/kustomize@main
      - name: Validate manifests
        run: ./scripts/validate.sh
