# https://fluxcd.io/flux/components/helm/helmreleases/
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: istio-cni
  namespace: istio-system
spec:
  releaseName: istio-cni
  interval: 30m
  chart:
    spec:
      chart: cni
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: flux-system
      interval: 12h
  values:
    profile: ambient
    cni:
      cniConfDir: /var/lib/rancher/k3s/agent/etc/cni/net.d
      cniBinDir: /var/lib/rancher/k3s/data/current/bin/
