# https://fluxcd.io/flux/components/helm/helmreleases/
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: istio-cni
  namespace: istio-system
spec:
  releaseName: istio-cni
  interval: 30m
  chart:
    spec:
      chart: cni
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: flux-system
      interval: 12h
      version: "*"
  values:
    profile: ambient
    # https://istio.io/latest/docs/ambient/install/platform-prerequisites/#k3s
    global:
      platform: k3s
      # In order to use native nftable rules instead of iptable rules, set this flag to true.
      nativeNftables: true
