---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./istio-ingress.yaml
  - ./ztunnel.yaml


patches:
  # set the version of all the istio components
  - patch: |-
      kind: will-be-ignored
      metadata:
        name: will-be-ignored
      spec:
        interval: 72h
        version: "1.22.3"
    target:
      kind: HelmRelease
