---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./istio-base.yaml
  - ./istio-cni.yaml
  - ./istio-ingress.yaml
  - ./istiod.yaml
  - ./ztunnel.yaml
  - ./cilium-allow-ambient.yaml
