---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./istio-base.yaml
  - ./istio-cni.yaml
  - ./istio-ingress.yaml
  - ./istiod.yaml
  - ./ztunnel.yaml
  - ./istio-metrics.yaml
  # - ./cilium-allow-ambient.yaml

patches:
  # set the version of all the istio components
  - patch: |-
      kind: will-be-ignored
      metadata:
        name: will-be-ignored
      spec:
        interval: 72h
        chart:
          spec:
            version: "1.23.0"
    target:
      kind: HelmRelease
